import '../src/styles/app.scss'
import Header from './Header'
import { Provider } from '../components/Client'
import { Toaster } from 'react-hot-toast'





export const metadata = {
  title: 'Todo APP',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
   <html lang='en'>
    <body >
    
    <Provider> 
   
   <>
   <Header/>
   {children}
      
      </>
      
    
     
     

      
   
      
      
     </Provider> 
     </body>

   </html>
      
    
  )
}
 